# Generated by Django 4.0.3 on 2022-03-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acessoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=50)),
                ('cnpj', models.IntegerField()),
                ('telefone', models.IntegerField()),
            ],
        ),
    ]
