# Generated by Django 4.0.3 on 2022-03-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acessoria',
            old_name='cnpj',
            new_name='CEP',
        ),
        migrations.AddField(
            model_name='acessoria',
            name='Bairro',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acessoria',
            name='Banco',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Nao')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acessoria',
            name='CPF',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acessoria',
            name='Capitao_Inicial',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acessoria',
            name='Cidade',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acessoria',
            name='Complemento',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acessoria',
            name='Data_Nascimento',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acessoria',
            name='Estado',
            field=models.CharField(choices=[('MG', 'Minas Gerais'), ('SP', 'Sao Paulo')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acessoria',
            name='ExpeditorRG',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acessoria',
            name='Imposto',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Nao')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acessoria',
            name='Nome_Fantasia',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acessoria',
            name='Nome_Mae',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acessoria',
            name='Numero',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acessoria',
            name='OcupacaoPrincipal',
            field=models.CharField(choices=[('0121101', 'Viveirista independente'), ('0159801', 'Apicultor(a) independente'), ('0159802', 'Criador(a) de animais domésticos independente')], default=1, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acessoria',
            name='OcupacaoSegundario',
            field=models.CharField(choices=[('0121101', 'Viveirista independente'), ('0159801', 'Apicultor(a) independente'), ('0159802', 'Criador(a) de animais domésticos independente')], default=1, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acessoria',
            name='RG',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acessoria',
            name='Rua',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acessoria',
            name='UF_RG',
            field=models.CharField(choices=[('MG', 'Minas Gerais'), ('SP', 'Sao Paulo')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
