# Generated by Django 4.0.3 on 2022-03-29 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0006_remove_acessoria_preco_delete_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.FloatField()),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='plataforma.acessoria')),
            ],
        ),
    ]
