# Generated by Django 4.0.3 on 2022-03-29 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0009_alter_produto_preco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='servico',
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.acessoria')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.produto')),
            ],
        ),
    ]
