# Generated by Django 4.0.3 on 2022-03-31 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0013_alter_produto_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.CharField(default=10, max_length=5),
            preserve_default=False,
        ),
    ]
