# Generated by Django 4.0.3 on 2022-03-31 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0015_pedidos_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='valor',
        ),
    ]
