# Generated by Django 4.0.3 on 2022-04-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0018_pedidos_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
