# Generated by Django 4.0.3 on 2022-04-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0019_alter_pedidos_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acessoria',
            name='CEP',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='acessoria',
            name='CPF',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='acessoria',
            name='RG',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='acessoria',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
    ]
