# Generated by Django 4.0.3 on 2022-04-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0022_rename_rua_acessoria_logradouro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acessoria',
            name='nome_Impresarial',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acessoria',
            name='tituloeleitor',
            field=models.CharField(max_length=100),
        ),
    ]
