# Generated by Django 4.0.3 on 2022-04-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0024_remove_acessoria_formaatuacao1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acessoria',
            name='email2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='acessoria',
            name='formaatuacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='acessoria',
            name='residencial_Bairro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='acessoria',
            name='residencial_CEP',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='acessoria',
            name='residencial_Cidade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='acessoria',
            name='residencial_Complemento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='acessoria',
            name='residencial_Estado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='acessoria',
            name='residencial_Numero',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='acessoria',
            name='residencial_logradouro',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
