# Generated by Django 4.0.3 on 2022-04-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0027_alter_acessoria_formaatuacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alterar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=200)),
                ('datanascimento', models.CharField(max_length=200)),
                ('nome', models.CharField(max_length=200)),
                ('nomeEmpresarial', models.CharField(max_length=200)),
                ('nacionalidade', models.CharField(max_length=200)),
                ('sexo', models.CharField(max_length=15)),
                ('nome_mae', models.CharField(max_length=200)),
                ('rg', models.CharField(max_length=200)),
                ('ExpeditorRG', models.CharField(max_length=200)),
                ('uf_rg', models.CharField(max_length=200)),
                ('Nome_Fantasia', models.CharField(max_length=200)),
                ('Capitao_Inicial', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=200)),
                ('Celular', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('OcupacaoPrimaria', models.CharField(max_length=200)),
                ('Ocupacao_Segundaria', models.CharField(max_length=200)),
                ('formaatuacao', models.CharField(max_length=200)),
                ('cep', models.CharField(max_length=8)),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=5)),
                ('complemento', models.CharField(max_length=20)),
                ('bairro', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('estadocnpj', models.CharField(max_length=2)),
                ('contagov', models.CharField(max_length=50)),
                ('senhagov', models.CharField(max_length=50)),
                ('cep2', models.CharField(blank=True, max_length=8, null=True)),
                ('lagradouro2', models.CharField(blank=True, max_length=100, null=True)),
                ('numero2', models.CharField(blank=True, max_length=5, null=True)),
                ('complemento2', models.CharField(blank=True, max_length=20, null=True)),
                ('bairro2', models.CharField(blank=True, max_length=100, null=True)),
                ('municipio2', models.CharField(blank=True, max_length=100, null=True)),
                ('estadocnpj2', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='acessoria',
            name='CEP',
            field=models.CharField(max_length=8),
        ),
    ]
