# Generated by Django 4.0.3 on 2022-04-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0028_alterar_alter_acessoria_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alterar',
            name='OcupacaoPrimaria',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='alterar',
            name='Ocupacao_Segundaria',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='alterar',
            name='formaatuacao',
            field=models.TextField(max_length=200),
        ),
    ]
