# Generated by Django 4.0.3 on 2022-05-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0029_alter_alterar_ocupacaoprimaria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baixar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=200)),
                ('Nome_Fantasia', models.CharField(max_length=200)),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=200)),
                ('datanascimento', models.CharField(max_length=8)),
                ('nome_mae', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('cep', models.CharField(max_length=8)),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=5)),
                ('complemento', models.CharField(max_length=20)),
                ('bairro', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('estadocnpj', models.CharField(max_length=2)),
                ('contagov', models.CharField(max_length=100)),
                ('senhagov', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='acessoria',
            name='logingov',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='acessoria',
            name='senhagov',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alterar',
            name='contagov',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alterar',
            name='datanascimento',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='alterar',
            name='senhagov',
            field=models.CharField(max_length=100),
        ),
    ]
