# Generated by Django 4.0.3 on 2022-05-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0030_baixar_alter_acessoria_logingov_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alterar',
        ),
        migrations.DeleteModel(
            name='Baixar',
        ),
        migrations.AlterField(
            model_name='acessoria',
            name='Capitao_Inicial',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='acessoria',
            name='ExpeditorRG',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='acessoria',
            name='OcupacaoPrincipal',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='acessoria',
            name='OcupacaoSegundario',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='acessoria',
            name='RG',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='acessoria',
            name='UF_RG',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='acessoria',
            name='celular',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='acessoria',
            name='nacionalidade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='acessoria',
            name='nome_Impresarial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='acessoria',
            name='sexo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='acessoria',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='acessoria',
            name='tituloeleitor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
