# Generated by Django 4.0.3 on 2022-05-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0031_delete_alterar_delete_baixar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acessoria',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
