# Generated by Django 4.0.3 on 2022-05-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0033_acessoria_faturamento_anual'),
    ]

    operations = [
        migrations.AddField(
            model_name='acessoria',
            name='prestacao',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='acessoria',
            name='revenda_mercadoria',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='acessoria',
            name='trasporte_de_carga',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
