# Generated by Django 4.0.3 on 2022-05-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0034_acessoria_prestacao_acessoria_revenda_mercadoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acessoria',
            name='contratacao',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='acessoria',
            name='funcionario',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
